@startuml
boundary CourseManagementUI
boundary CourseServiceAPI

control CourseManagementController

entity Course
entity Instructor
entity Student
entity CourseMaterial

left to right direction
@enduml